### ISSUE TITLE
Insert None as DEFAULT value

### ISSUE THREAD

**Issue by Yan-Zhelanov** [ClickHouse/clickhouse-connect#153] opened 2023-03-23 11:37 UTC
My creation DDL of the table:
```sql
create table if not exists test
(
    date    DateTime default toDateTime('2022-03-03 11:00:00'),
    item_id UInt64   default -1
)
    engine = MergeTree PARTITION BY toYYYYMMDD(date)
        ORDER BY (date, item_id)
        SETTINGS index_granularity = 8192;
```
I want to insert `None` as `DEFAULT`:
```python
client.insert(
    table='kvi_cluster_test',
    data=[
        (datetime(1970, 2, 2), 1),
        (datetime(1970, 2, 2), None),
        (None, 1),
    ],
    column_names=['date', 'item_id'],
)
```
But when I did that, I got an exception:
```
clickhouse_connect.driver.exceptions.ProgrammingError: Internal serialization error.  This usually indicates invalid data types in an inserted row or column
```
Expected behaviour: when column type is Non-Nullable and data has `None` values, this values interpret as `DEFAULT` SQL keyword.

**Comment by genzgd** [comment] 2023-05-02 22:05
This is a duplicate of https://github.com/ClickHouse/clickhouse-connect/issues/107.  Unfortunately I'm not sure at this point when we'll get to that enhancement.

**Closed by genzgd** 2023-05-02 22:05 UTC
Labels: enhancement
