### ISSUE TITLE
Calling UNION DISTINCT throws "StreamFailureError" or returns wrong answer

### ISSUE THREAD

**Issue by lqhl** [ClickHouse/clickhouse-connect#350] opened 2024-05-20 10:08 UTC
### Describe the bug

Calling UNION DISTINCT throws `StreamFailureError` or returns wrong answer.

### Example of `StreamFailureError`

Code:

```python
import clickhouse_connect

client = clickhouse_connect.get_client(host='localhost', username='default', password='')
result = client.query("SELECT 1 as d, '[test]' as a UNION DISTINCT SELECT 1 as d, '[test]' as a")
print(result.result_rows)
```

clickhouse-connect logs

```shell
$ python3 tmp.py
Traceback (most recent call last):
  File "/home/qliu/workspace/mqdb/build/programs/tmp.py", line 4, in <module>
    result = client.query("SELECT 1 as d, '[test]' as a UNION DISTINCT SELECT 1 as d, '[test]' as a")
  File "/home/qliu/.local/lib/python3.10/site-packages/clickhouse_connect/driver/client.py", line 201, in query
    return self._query_with_context(query_context)
  File "/home/qliu/.local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 223, in _query_with_context
    query_result = self._transform.parse_response(byte_source, context)
  File "/home/qliu/.local/lib/python3.10/site-packages/clickhouse_connect/driver/transform.py", line 68, in parse_response
    first_block = get_block()
  File "/home/qliu/.local/lib/python3.10/site-packages/clickhouse_connect/driver/transform.py", line 63, in get_block
    raise StreamFailureError(message) from None
clickhouse_connect.driver.exceptions.StreamFailureError: 1      [test]
```

### Example of the wrong answer

Code:

```python
import clickhouse_connect

client = clickhouse_connect.get_client(host='localhost', username='default', password='')
result = client.query("SELECT 1 as d, 'test' as a UNION DISTINCT SELECT 1 as d, 'test' as a")
print(result.result_rows)
```

clickhouse-connect logs

```shell
$ python3 tmp.py
[]
```

The answer returned by clickhouse-client is right:

```sql
:) SELECT 1 as d, 'test' as a UNION DISTINCT SELECT 1 as d, 'test' as a

SELECT
    1 AS d,
    'test' AS a
UNION DISTINCT
SELECT
    1 AS d,
    'test' AS a

Query id: c3311c46-18f5-4be8-91c8-0db3fccc60ba

┌─d─┬─a────┐
│ 1 │ test │
└───┴──────┘

1 row in set. Elapsed: 0.001 sec.
```

#### Environment
* clickhouse-connect version: 0.7.8
* Python version: 3.10.12
* Operating system: Ubuntu 22.04

#### ClickHouse server

* ClickHouse Server version: v23.3.2.1-lts

**Comment by genzgd** [comment] 2024-05-20 11:16
Unfortunately this appears to be a bug in ClickHouse itself.  I can reproduce it on 23.3 and earlier versions -- the problem is that ClickHouse is sending an invalid column count using Native format over HTTP for that particular query.  It appears to be fixed in later versions, including 23.8.14, the earlier LTS version that is still supported.

**Closed by genzgd** 2024-05-20 11:16 UTC
Labels: bug
