### ISSUE TITLE
Maybe this is a bug or Feature that cannot set the size of http connect pool

### ISSUE THREAD

**Issue by campanulamediuml** [ClickHouse/clickhouse-connect#190] opened 2023-05-11 09:21 UTC
### Describe the bug
the size of HTTP connect pool cannot be set

### Steps to reproduce
No

### Expected behaviour
connect_timeout will be more than I set

### Code example
```python
import clickhouse_connect
clickhouse_connect.get_client(host...   , connect_timeout=10)
```
when host is a url can request  but no clickhouse serve on it 

and than my application have to wait for more than 30 seconds

By reading source code, I found that  DEFAULT_KEEP_COUNT in clickhouse_connect.driver.httputil was set as 3

#### Environment
* clickhouse-connect version:0.5.20
* Python version:3.8.x
* Operating system:all

**Comment by genzgd** [comment] 2023-05-11 15:22
DEFAULT_KEEP_COUNT and other *KEEP* settings don't affect the connection timeout.

In testing this I found the issue is actually that the urllib3 library will try all of the IP addresses exposed for the host name.  So, for example, when I connect to an AWS host that lists 3 addresses in DNS, it will try to connect to each IP address listed for the connect_timeout of 10 seconds, and then fail, for a total of 30 seconds.

So other than reducing the number of actual IP addresses or reducing the connect_timeout from 10 seconds to something lower, this is not something that can be fixed in the `clickhouse-connect code`.

**Closed by genzgd** 2023-05-11 15:22 UTC
Labels: bug
