### ISSUE TITLE
error when try to select datetime from dataset

### ISSUE THREAD

**Issue by xl631212** [ClickHouse/clickhouse-connect#154] opened 2023-03-24 06:53 UTC
### clickhouse-connect and/or ClickHouse server logs
/tmp/ipykernel_4020/3088587567.py:5 in <module>                                                  │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_4020/3088587567.py'                         │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/driver/client. │
│ py:156 in query                                                                                  │
│                                                                                                  │
│   153 │   │   if query_context.is_command:                                                       │
│   154 │   │   │   response = self.command(query, parameters=query_context.parameters, settings   │
│   155 │   │   │   return QueryResult([response] if isinstance(response, list) else [[response]   │
│ ❱ 156 │   │   return self._query_with_context(query_context)                                     │
│   157 │                                                                                          │
│   158 │   def query_column_block_stream(self,                                                    │
│   159 │   │   │   │   │   │   │   │     query: str = None,                                       │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/driver/httpcli │
│ ent.py:201 in _query_with_context                                                                │
│                                                                                                  │
│   198 │   │   │   │   │   │   │   │   │    retries=self.query_retries,                           │
│   199 │   │   │   │   │   │   │   │   │    server_wait=not context.streaming)                    │
│   200 │   │   byte_source = RespBuffCls(ResponseSource(response))  # pylint: disable=not-calla   │
│ ❱ 201 │   │   query_result = self._transform.parse_response(byte_source, context)                │
│   202 │   │   if 'X-ClickHouse-Summary' in response.headers:                                     │
│   203 │   │   │   try:                                                                           │
│   204 │   │   │   │   summary = json.loads(response.headers['X-ClickHouse-Summary'])             │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/driver/transfo │
│ rm.py:62 in parse_response                                                                       │
│                                                                                                  │
│    59 │   │   │   block_num += 1                                                                 │
│    60 │   │   │   return result_block                                                            │
│    61 │   │                                                                                      │
│ ❱  62 │   │   first_block = get_block()                                                          │
│    63 │   │   if first_block is None:                                                            │
│    64 │   │   │   return NumpyResult() if context.use_numpy else QueryResult([])                 │
│    65                                                                                            │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/driver/transfo │
│ rm.py:44 in get_block                                                                            │
│                                                                                                  │
│    41 │   │   │   │   │   else:                                                                  │
│    42 │   │   │   │   │   │   col_type = col_types[col_num]                                      │
│    43 │   │   │   │   │   context.start_column(name)                                             │
│ ❱  44 │   │   │   │   │   column = col_type.read_column(source, num_rows, context)               │
│    45 │   │   │   │   │   result_block.append(column)                                            │
│    46 │   │   │   except Exception as ex:                                                        │
│    47 │   │   │   │   source.close()                                                             │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/datatypes/base │
│ .py:128 in read_column                                                                           │
│                                                                                                  │
│   125 │   │   :return: The decoded column data as a sequence and the updated location pointer    │
│   126 │   │   """                                                                                │
│   127 │   │   self.read_column_prefix(source)                                                    │
│ ❱ 128 │   │   return self.read_column_data(source, num_rows, ctx)                                │
│   129 │                                                                                          │
│   130 │   def read_column_data(self, source: ByteSource, num_rows: int, ctx: QueryContext) ->    │
│   131 │   │   """                                                                                │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/datatypes/base │
│ .py:143 in read_column_data                                                                      │
│                                                                                                  │
│   140 │   │   elif self.nullable:                                                                │
│   141 │   │   │   column = self._read_nullable_column(source, num_rows, ctx)                     │
│   142 │   │   else:                                                                              │
│ ❱ 143 │   │   │   column = self._read_column_binary(source, num_rows, ctx)                       │
│   144 │   │   return self._finalize_column(column, ctx)                                          │
│   145 │                                                                                          │
│   146 │   def _read_nullable_column(self, source: ByteSource, num_rows: int, ctx: QueryContext   │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/datatypes/temp │
│ oral.py:179 in _read_column_binary                                                               │
│                                                                                                  │
│   176 │   │   tz_info = ctx.active_tz or self.tzinfo                                             │
│   177 │   │   if tz_info:                                                                        │
│   178 │   │   │   return self._read_binary_tz(column, tz_info)                                   │
│ ❱ 179 │   │   return self._read_binary_naive(column)                                             │
│   180 │                                                                                          │
│   181 │   def _read_binary_tz(self, column: Sequence, tz_info: tzinfo):                          │
│   182 │   │   new_col = []                                                                       │
│                                                                                                  │
│ /home/op_admin/.conda/envs/pytorch/lib/python3.9/site-packages/clickhouse_connect/datatypes/temp │
│ oral.py:200 in _read_binary_naive                                                                │
│                                                                                                  │
│   197 │   │   prec = self.prec                                                                   │
│   198 │   │   for ticks in column:                                                               │
│   199 │   │   │   seconds = ticks // prec                                                        │
│ ❱ 200 │   │   │   dt_sec = dt_from(seconds)                                                      │
│   201 │   │   │   app(dt_sec.replace(microsecond=((ticks - seconds * prec) * 1000000) // prec)   │
│   202 │   │   return new_col                                                                     │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: year 51805701 is out of range

**Comment by genzgd** [comment] 2023-03-24 07:24
What column type was in the query?  Can you create a small query to reproduce?

**Comment by xl631212** [comment] 2023-03-24 08:21
datetime64, it can be produced by following:
data:
[image: 截屏2023-03-24 16.20.25.png]
code:
client.command("""
CREATE TABLE default.myscale_reddit_covid_analysis
(
    id  UInt32,
    subreddit String,
    body String,
    sentiment Float64,
    created_utc datetime64
)
ENGINE = MergeTree ORDER BY id""")

client.query(f"""
SELECT *,distance('topK={top_k}')(embeddings, {emb_query}) as dist
FROM default.myscale_reddit_covid_analysis
""")

Geoff Genz ***@***.***> 于2023年3月24日周五 15:24写道：

**Comment by genzgd** [comment] 2023-03-24 08:32
Thanks for the additional detail!  I think the problem is that DateTime64 should be created with a precision.  It looks like if you don't specify a precision, it actually creates a DateTime64(3) (millisecond precision), but ClickHouse doesn't return the (3) in the Native format on the query and clickhouse-connect doesn't know the precision to convert the raw integer value.

The simplest workaround is to change your create table to `created_utc DateTime64(3)`.  I'll get a fix for this edge case in the next release.

**Comment by genzgd** [comment] 2023-03-26 06:14
It turns out that I can't reproduce this locally.  ClickHouse has no `distance` function as far as I can tell.  Is it a user defined function?  What datatypes does it return?   Does the query work without the `dist` column?

**Closed** 2023-04-04 18:35 UTC
Labels: bug, need info
