### ISSUE TITLE
http cannot support large data select request

### ISSUE THREAD

**Issue by danelfedor** [ClickHouse/clickhouse-connect#56] opened 2022-10-19 07:08 UTC
use http connect to clickhouse is considerablely slower than connect use 9000 port like clickhouse-client， clickhouse_driver Client
I Try to query same table for 5000 lines of data use clickhouse_connect.client and our old connection use clickhouse_driver.Client
clickhouse_driver.Client takes about **15.1**s to get all data back to dataframe
clickhouse_connect use 13min 22s
![image](https://user-images.githubusercontent.com/29364954/196620152-17d8802c-dc98-4149-a8ab-8cf6b6e886db.png)
I try to stop the query at middle , almost all time taken by socket recv buffer
![image](https://user-images.githubusercontent.com/29364954/196620469-416b4747-c0f4-428f-be31-9c631321fae5.png)
Please consider to use 9000 port directly other than http, to improve select performance

**Comment by genzgd** [comment] 2022-10-19 09:35
Can you give some more details about the data you are retrieving?  How many bytes?  What datatypes are you reading?  Is it possible that you have issues with your HTTP connection?

Also could you try the same query without using dataframes?  Just the simple client.query method?

Benchmarks for most queries show that ClickHouse Connect is slower than clickhouse-driver for some datatypes (in particular strings) but faster for others (such as integers).   The amount of bytes read over the network is almost exactly the same, so changing the interface from Native to HTTP should not have such a dramatic effect, so I strongly believe something else is going on.

**Comment by genzgd** [comment] 2022-10-19 09:57
Actually this may be a problem with the HTTP connection pool.  Does your application use multiple threads or multiple processes?

**Comment by genzgd** [comment] 2022-10-19 11:05
For simple operation there is not a big difference between ClickHouse Connect and clickhouse-driver:

```python
import timeit

cc_setup = """
import clickhouse_connect
cc_client = clickhouse_connect.get_client(host='play.clickhouse.com', username='play', password='clickhouse', port=443, secure=True)
"""

cc_query = "cc_client.query('SELECT * FROM hackernews LIMIT 5000')"
print (f'ClickHouse Connect 10 queries: {timeit.timeit(cc_query, setup=cc_setup, number=10)} seconds')

d_setup = """
from clickhouse_driver import Client
d_client = Client(host='play.clickhouse.com', user='play', password='clickhouse', port=9440, secure=True)
"""

d_query = "d_client.execute('SELECT * FROM hackernews LIMIT 5000')"
print (f'ClickHouse Driver 10 queries: {timeit.timeit(d_query, setup=d_setup, number=10)} seconds')
```

Results of a couple of runs:

```
ClickHouse Connect 10 queries: 3.815127167 seconds
ClickHouse Driver 10 queries: 3.631310749999999 seconds

ClickHouse Connect 10 queries: 4.094857 seconds
ClickHouse Driver 10 queries: 3.4274464580000004 seconds
```

So there is definitely something unusual about your setup -- I would very much like to figure out what the difference is, so any additional information you could provide would be much appreciated.

**Comment by danelfedor** [comment] 2022-10-20 01:44
> For simple operation there is not a big difference between ClickHouse Connect and clickhouse-driver:
> 
> ```python
> import timeit
> 
> cc_setup = """
> import clickhouse_connect
> cc_client = clickhouse_connect.get_client(host='play.clickhouse.com', username='play', password='clickhouse', port=443, secure=True)
> """
> 
> cc_query = "cc_client.query('SELECT * FROM hackernews LIMIT 5000')"
> print (f'ClickHouse Connect 10 queries: {timeit.timeit(cc_query, setup=cc_setup, number=10)} seconds')
> 
> d_setup = """
> from clickhouse_driver import Client
> d_client = Client(host='play.clickhouse.com', user='play', password='clickhouse', port=9440, secure=True)
> """
> 
> d_query = "d_client.execute('SELECT * FROM hackernews LIMIT 5000')"
> print (f'ClickHouse Driver 10 queries: {timeit.timeit(d_query, setup=d_setup, number=10)} seconds')
> ```
> 
> Results of a couple of runs:
> 
> ```
> ClickHouse Connect 10 queries: 3.815127167 seconds
> ClickHouse Driver 10 queries: 3.631310749999999 seconds
> 
> ClickHouse Connect 10 queries: 4.094857 seconds
> ClickHouse Driver 10 queries: 3.4274464580000004 seconds
> ```
> 
> So there is definitely something unusual about your setup -- I would very much like to figure out what the difference is, so any additional information you could provide would be much appreciated.

Each line of data should have about 0.8-1.2 MB data with 20 columns of buffer and few columns of timestamp and int32, unum8 
If I only query 1 line speed is about same 
![image](https://user-images.githubusercontent.com/29364954/196835454-93b5ea5d-3989-4043-b1f8-0eaed0cf6f58.png)
if I query 10 lines time going to double 
![image](https://user-images.githubusercontent.com/29364954/196835842-3d4567bd-19f8-4a4a-af8c-a7ae9cfd85c6.png)
here is about 100 and 1000 lines 
![image](https://user-images.githubusercontent.com/29364954/196836031-d335d453-92d3-4c31-997a-a272b775a522.png)
![image](https://user-images.githubusercontent.com/29364954/196836293-d29f09bd-edfe-474f-b84f-1510903adb8f.png)

**Comment by danelfedor** [comment] 2022-10-20 02:00
I try to re-execute this 5000 lines sql multiple times best performance going like this, 
![image](https://user-images.githubusercontent.com/29364954/196838406-335d4283-2c19-48e5-87b8-fe6724235e28.png)

**Comment by genzgd** [comment] 2022-10-20 02:57
Thanks for such a detailed response; that's very helpful information.

For your use case with such large rows I'd guess that clickhouse-driver has a few advantages.  It has more C optimizations around Strings (which I'm assuming make up the majority of your data), it has better compression (lz4 vs gzip) which will certainly have an effect at large volume, and it reads in more of a block level/streaming fashion, while ClickHouse Connect currently loads the entire HTTP response into memory at once and then must "pivot" it from column to row format.  

So I don't think the issue is really the HTTP vs the native interface, but there is definitely room for improvement in handling very large query results (especially with large rows).  I would love to get to such optimizations when time permits, but I don't know how soon that will happen.  Until then I don't know that there's any reason for you to switch.  clickhouse-driver is a mature, well tested and well engineered project that sounds like it is currently a better fit for your application.

I'll leave this open as a reminder that there is significant room for improvement for large result sets and rows.  Thanks again for raising the issue.

**Comment by genzgd** [comment] 2023-01-09 00:36
@danelfedor -- again thanks for your detailed investigation.

The next release (version 0.5.0  will be out early this week) should improve HTTP performance, especially if you turn off compression until we find a fix for https://github.com/ClickHouse/clickhouse-connect/issues/89.

There's also room for improvement for Pandas DataFrames -- see https://github.com/ClickHouse/clickhouse-connect/issues/90.

Finally I agree that using the ClickHouse native interface can make things even better, so that is now a planned feature.  https://github.com/ClickHouse/clickhouse-connect/issues/91

I'm going to close this issue in favor of the three issues above to make them easier to track, but please let us know if there's anything that those don't cover.l

**Closed by genzgd** 2023-01-09 00:36 UTC
Labels: enhancement
