### ISSUE TITLE
bug: list index out of range coming while hitting query

### ISSUE THREAD

**Issue by hash-data** [ClickHouse/clickhouse-connect#318] opened 2024-03-16 11:12 UTC
### Describe the bug
Error coming from clickhouse connect while running the query :
```
select CAST(json_str AS JSON) AS json_obj from test.json_str_table1;
```
<img width="877" alt="Screenshot 2024-03-16 at 16 40 11" src="https://github.com/ClickHouse/clickhouse-connect/assets/111491139/d23b85ea-fbb4-45c8-972d-0839c71265a0">

### Steps to reproduce
1. Run the query in clickhouse
```
CREATE TABLE test.json_str_table1
(
    `json_str` String
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192;
```
2.  Insert some data in same 
```
insert into test.json_str_table1 (json_str) values ('{"a":"b"}');
 ```
3. Run the query below: 
```
select CAST(json_str AS JSON) AS json_obj from test.json_str_table1;
```

### Expected behaviour
As result is coming is clickhouse playground 
<img width="1072" alt="Screenshot 2024-03-16 at 16 38 13" src="https://github.com/ClickHouse/clickhouse-connect/assets/111491139/6e1ac5c3-e3e2-420c-836b-55deeac10e58">

### Code example
```python
import clickhouse_connect
```

### clickhouse-connect and/or ClickHouse server logs
Stack trace: 
```
-16 16:22:11,370:ERROR:root:on the exception : list index out of range
Traceback (most recent call last):
  File "/Users/apple/Desktop/Datazip/bi/superset/db_engine_specs/base.py", line 1562, in execute
    cursor.execute(query)
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/dbapi/cursor.py", line 51, in execute
    self.data = query_result.result_set
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/query.py", line 254, in result_set
    return self.result_rows
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/query.py", line 272, in result_rows
    for block in stream:
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/common.py", line 195, in __next__
    return next(self.gen)
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/query.py", line 292, in _row_block_stream
    for block in self._column_block_stream():
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/transform.py", line 75, in gen
    next_block = get_block()
  File "/Users/apple/Desktop/Datazip/bi/venvdbt/lib/python3.9/site-packages/clickhouse_connect/driver/transform.py", line 45, in get_block
    col_type = col_types[col_num]
IndexError: list index out of range
```
#### Environment
* clickhouse-connect version: tries 0.6.22 and 0.7.3
* Python version: Python 3.9.13
* Operating system: MacOs

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by genzgd** [comment] 2024-03-16 11:18
Duplicate of https://github.com/ClickHouse/clickhouse-connect/issues/298.  We no longer actively support the experimental JSON type, and I have no idea what Superset would do with it anyway.

**Closed by genzgd** 2024-03-16 11:18 UTC
Labels: bug
